fix:when skelton data destory clean all data.
cocos-creator/engine-native pull request #3800
Opened 2021-08-05 06:13 UTC by zhakesi

previous version the info still exists in the data map,
this cause initializing skeleton failed second time.
[https://forum.cocos.org/t/topic/118416/11](https://forum.cocos.org/t/topic/118416/11)

2021-08-05 08:24 UTC, mmyduckx requested changes

2021-08-05 08:24 UTC, mmyduckx commented on cocos/editor-support/spine-creator-support/SkeletonDataMgr.cpp
> +        auto &texturesIndex = info->texturesIndex;
`auto &texturesIndex = info->texturesIndex;`
这行没用了吧

2021-08-05 08:42 UTC, zhakesi commented on cocos/editor-support/spine-creator-support/SkeletonDataMgr.cpp
> +        auto &texturesIndex = info->texturesIndex;
是，删了

2021-08-05 08:50 UTC, mmyduckx approved these changes

2021-08-05 09:15 UTC, PatriceJiang commented on cocos/editor-support/spine-creator-support/SkeletonDataMgr.cpp
> -    dataIt->second->retain();
如果不需要 retain,  那方法 `retainByUUID` 是不是要改成 `findByUUID`, `releaseByUUID` 改成 `deleteByUUID` ?

2021-08-05 10:09 UTC, PatriceJiang commented on cocos/editor-support/spine-creator-support/SkeletonDataMgr.cpp
> -    dataIt->second->retain();
感觉 Ref 机制本身没有问题, 应该是 retain/release 没匹配

2021-08-06 08:24 UTC, PatriceJiang approved these changes

2021-08-06 08:24 UTC, mmyduckx approved these changes

2021-08-06 08:33 UTC, merged